### ISSUE TITLE
US1: Пользователь может войти в свой gmail ящик 

### ISSUE THREAD

**Issue by astupak** [blockemail/blockey#1]

**Comment by astupak** [comment]
Реализовать класс SmtpClient 
Реализовать метод connectToHost

**Comment by astupak** [comment]
Реализовать класс SmtpClient 
Реализовать метод Login

**Comment by astupak** [comment]
Реализовать форму ввода логина и пароля

**Comment by AnastasyaK** [comment]
Реализовать валидацию поля email
